import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../styles/globals.scss";

const regular = localFont({
  src: "../fonts/PlusJakartaSans-Regular.ttf",
  variable: "--regular-font",
});

const medium = localFont({
  src: "../fonts/PlusJakartaSans-Medium.ttf",
  variable: "--medium-font",
});

const bold = localFont({
  src: "../fonts/PlusJakartaSans-SemiBold.ttf",
  variable: "--bold-font",
});

const loraregular = localFont({
  src: "../fonts/PlusJakartaSans-Regular.ttf",
  variable: "--lora-font",
});

const loramedium = localFont({
  src: "../fonts/PlusJakartaSans-Medium.ttf",
  variable: "--loramed-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
