import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../styles/globals.scss";

import { initServerI18next, getT, getResources, generateI18nStaticParams } from 'next-i18next/server'
import { I18nProvider } from 'next-i18next/client'
import i18nConfig from '../../i18n.config'


//Translation

const regular = localFont({
  src: "./fonts/PlusJakartaSans-Regular.ttf",
  variable: "--regular-font",
});

const medium = localFont({
  src: "./fonts/PlusJakartaSans-Medium.ttf",
  variable: "--medium-font",
});

const bold = localFont({
  src: "./fonts/PlusJakartaSans-SemiBold.ttf",
  variable: "--bold-font",
});

const loraregular = localFont({
  src: "./fonts/Lora-Regular.ttf",
  variable: "--lora-font",
});

const lorabold = localFont({
  src: "./fonts/Lora-SemiBold.ttf",
  variable: "--lorabold-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${regular.variable} ${medium.variable} ${bold.variable} ${loraregular.variable} ${lorabold.variable}`}>
      <body>{children}</body>
    </html>
  );
}
